### ISSUE TITLE
choose main color for catalysts

### ISSUE THREAD

**Issue by wileyandco** [wileyandco/thehumanarray#14]

**Comment by wileyandco** [comment]
@CarrieTHA testing the (at) ability just to be sure.

**Comment by CarrieTHA** [comment]
This is great! I want to leave the dark purple for the Catalyst space icon to have it stand out from the rest in the "Home" collection. However, can we use the same icon with a white background for the Start Here section? What do you think?

So I was thinking that the color mapping would look like this: 
- Catalyst space (eventually there may be cohorts of this, but each cohort would only see their own): dark purple background, light purple icon
- Catalyst start here: white background with dark purple (similar to the eye)
- Individual Catalyst spaces: They would be color coded to the Array that they associate with for navigation purposes for now. Thoughts?

**Comment by wileyandco** [comment]
That all sounds good to me. Sending this directly from the email btw :) I'm
thinking for the individual ones that we use the main color and then that
same color's darker or lighter tint to make it really distinct and
secondary to the main category. Wdyt?

**Comment by wileyandco** [comment]
@CarrieTHA fyi the image didn't take from the email I sent so attaching here. Last time I used this it was all for code so had never tried it. 

![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/41b07918-2eed-4bcc-83b6-6f777f21861f)

**Comment by CarrieTHA** [comment]
I think I like the far right! The darker with the lighter as the icon. The
middle one doesn't feel like enough contrast.
