### ISSUE TITLE
Wisdom Well Branding

### ISSUE THREAD

**Issue by wileyandco** [wileyandco/thehumanarray#18]

**Comment by wileyandco** [comment]
Hey @CarrieTHA - got your pages invites, doc, and made this project and one for the pages themselves. Just an fyi :)

**Comment by CarrieTHA** [comment]
Awesome! I am starting to create a section in the Google doc that outlines the marketing materials. If we want to do a call next week to walk through it, I am game! I know there are still some missing pieces, but hopefully this is shaping up to get things rolling!

**Comment by wileyandco** [comment]
Great! I’m free except Monday all day (traveling) and Wednesday morning
next week. A call would be great so I know what sections and things we may
need for the pages and google doc sounds great. I have some ideas for the
overall branding for the events and figured I’d start there while you get
organized. Knowing how he specific parts of the event though would
be helpful. From what I’m finding in the doc so far is it going to be:

Overall promotion: Wisdom Well

Quarterly promotion: Wisdom Well, Nourish (Q1)

Monthly promotion: Wisdom Well, Nourish, Community (January)



Individual gathering spaces

Spark host resources/materials

- - gathering style ideas
- editable invites
- host introduction example and why we are here bullet points
Monthly Live event stream
Recording
Communal meal
Discussion: called “Well Work”?
- book club style questions or discussion prompts?

If this is still in flux, that’s fine just thinking about calling things
out with icons, illustrations, or photos.

**Comment by wileyandco** [comment]
Headers @CarrieTHA 

![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/375be242-dfe3-4271-8b70-4d9af6fd2c83)



![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/936edf07-3273-405c-b30a-20add945f6eb)

**Comment by wileyandco** [comment]
@CarrieTHA https://app.hubspot.com/email/40088323/edit/148954513954/content (does this link work?)
The email template for Wisdom Well Sales in up in Hubspot. Let me know if you need help with sections or adding in icons or such as it solidifies.
