### ISSUE TITLE
Wisdom Well Community Pages

### ISSUE THREAD

**Issue by wileyandco** [wileyandco/thehumanarray#19]
Welcome we will add to this - coming soon. Calendar invite. Jeannette will put in header image and update fonts/sections as they come in.

**Comment by wileyandco** [comment]
@CarrieTHA This came out too dark. It should be 50% blue, but then you also have to 50% the transparency of the image too and add the tileable static. Can you send me the canva you made it in? I can't find it.

![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/e3b03011-3a77-4a3b-9f43-7f60159d39a7)

**Comment by CarrieTHA** [comment]
I knew it wasn't quite right! I shared them with you via Canva. Let me know
if you can't find.

**Comment by wileyandco** [comment]
@CarrieTHA Thanks. Also apparently the static should go over the color too when layered. All set in there now! Note, I did some creative kerning and now the "well" text is broken up. Assuming it won't change, but just in case you're using this as a template for other things. It won't let me update the event graphic in Mighty since I didn't create the event, so here's the image exported too.  
![Wisdom Well MN Event Header (1624 x 696 px) (2)](https://github.com/wileyandco/thehumanarray/assets/78058722/63e5a230-4f14-4a4a-b87e-2b6cfd381557)

**Comment by wileyandco** [comment]
@CarrieTHA Sorry it exported darker than the preview. 40% for both is the new winner. New graphic attached. 
![Wisdom Well MN Event Header (1624 x 696 px) (3)](https://github.com/wileyandco/thehumanarray/assets/78058722/aeeb3f3b-0df9-4c8c-8b6c-257530b183cd)

**Comment by CarrieTHA** [comment]
Ah!! There ya go. Thank you. I can update the community now too. And yes,
this is helpful as ill resize for various different places.
