### ISSUE TITLE
Wisdom Well Host Invitation

### ISSUE THREAD

**Issue by CarrieTHA** [wileyandco/thehumanarray#21]
Of the various resources that we want to provide to those that sign-up to host a gathering, the highest priority is the invitation that a host will send to their guests. That way as we start to promote and people sign up, they can turn around and start inviting their friends. 

Host invitation - for host to send to guests
Editable so they can customize as they'd like
Include sections that give them direction and guidance as to what information to provide
Theme (ours+theirs?)
Why
When
What to expect
What to bring
RSVP

**Comment by wileyandco** [comment]
@CarrieTHA Awesome, tbc this will be canva? We could also/or make an editable pdf with those fields.

**Comment by CarrieTHA** [comment]
Yes, I think Canva will be great for this.

**Comment by wileyandco** [comment]
@CarrieTHA This is up in https://www.canva.com/design/DAF2xgjYnLM/ofvor_mK0bsMMcGCQ3urBA/edit for your thoughts.
