### ISSUE TITLE
Website Reorg

### ISSUE THREAD

**Issue by CarrieTHA** [wileyandco/thehumanarray#23]
Reorganize the website to create the expanded view of what THA is / offers. 

I added you to a Miro board where I have been organizing thoughts. 
![THA Brainstorming - Website New (12_23)](https://github.com/wileyandco/thehumanarray/assets/146997680/7a40aed4-08f0-422c-bbf9-5e237791ecfa)

I think (but you tell me) the first place to start that would be most supportive before you bring a beautiful new being into this world :D is the graphic that depicts the water wheel. We can jump on and discuss what that looks like and I played a bit with it in the Miro board as well where I was writing down the visuals that came up for me when Sarah and I have our philosophy / wisdom nailed down more.

**Comment by wileyandco** [comment]
Hey @CarrieTHA This looks great - love the detail! Can you send me the miro board? Would love to know what visuals. I'm free tomorrow anytime 11-330, but would love to do earlier so I have time to actually work on it too. Are the yellow ones the wheels? Especially appreciating the buckets in pink. This is definitely enough to go on to build out a new homepage, but happy to focus on the water wheel graphic for now if that feels the most complete and worthy of attention. Appreciate you. Talk soon!

**Comment by CarrieTHA** [comment]
Thanks! It sent an invite to your email, but here's a link as well. I think
it will give you edit access since I sent the other email, but let me know
if not.

https://miro.com/app/board/uXjVOss3e10=/

Also, I know this may be too on the nose, but Sarah said "oh, I wonder if
the THA logo could be the water wheel with the spikes and such!".

So while that may not be exactly what works for a logo, we both got chills
realizing it looks like that already. 🤯😳💖

Feel free to dig into the whole site! I just know that we can manage by
duplicating pages if needed for the short term on some of it, but that
image is not in our wheelhouse to make. 😂

**Comment by wileyandco** [comment]
Hey @CarrieTHA the first draft of the site and the well graphic are up on https://www.thehumanarray.com/home-new

Right now the graphic is up top on desktop, but I think on mobile/tablet it makes more sense to start with an intro of some sort so it switches on those. Also, you can see I added a description for context and organized the website into "facets", which may not be the right word, but felt good to me for now. Like of a person or personality, or a shining light. We could also add anchor links or buttons from each of these, but I didn't want to get too in the weeds before the layout itself is in a good place. 

Happy to update in Miro too if that is helpful, but basically I wanted to pull apart Catalysts and put the marketplace idea both with "growth" and a bit into "kindred connections"/podcasts, since the people you interview are prime people to be catalysts. Then seekers get the community/social bucket. Eventually each of the buckets could have multiple callout sections under them, like the Directory or Retreats once those exist.

One thing from the Miro I'd love to have you two re-work into the copy is "living system," since that goes really nicely with the wheel metaphor and categorizing. Obviously all the copy could use a look-over. 

Let me know if you want to chat through anything (in the morning assuming you're out for the day). 

Best,
Jeannette

**Comment by CarrieTHA** [comment]
Hi! Ok, Sarah and I finally had a chance to look through and chat on the updated look. Here are our thoughts: 
- We like the cups on the wheel as they feel like moons :D however, the overall feel of the wheel feels a bit heavy. It feels different than the rest of the branding in that way and we'd love to have it more aligned with that feel. I did a TERRIBLE sketch here as Sarah and I were talking after I did a little inspirational research. This image is from Twisted Sage of the Ether element. I liked how it was more aligned with the WW as well as the sacred geometry of THA. We liked incorporating more of that into the wheel which then would reduce the weight. Hopefully, you can parse out what I was trying to get at. https://www.canva.com/design/DAF429tprxA/QJ6EwzwfWFFyM49f5CHHpg/edit?utm_content=DAF429tprxA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
- I like the shapes of the water and sunset. I liked it better when it has the purple sky on the desktop version. We like the concept and I feel like that flows a lot with what is currently on the homepage, but the pictures don't quite feel right. I think a sky image that is a little lighter, more colored on the purple/blue side rather than the yellow. I can do some digging on images and see if I can find some that feel good. And perhaps it is one of those things where a plain color incorporated would look good the way the current homepage blends both. 
- I see what you are saying about mobile vs. desktop, and I agree that feels right. However, it feels a little too separated. Maybe if we find the right sky photo a color from that could blend it so that it feels it flows from one to the next a little more intentionally. 

Let me know if you want to chat tomorrow! I am open until 11am.

**Comment by CarrieTHA** [comment]
I found a couple of other inspirational symbols. These are all for Ether as one of the elementals. 

this one is just a nice representation of all of the elements, perhaps as inspiration for the inside of the circle. But I would say the least inspirational. Just that Ether is at the center of them all. 
![Screen Shot 2024-01-03 at 2 49 01 PM](https://github.com/wileyandco/thehumanarray/assets/146997680/8432e872-015d-4db7-8f4f-0dcff8dd0650)

The one in the very center feels a bit like what I was trying to draw, but simpler. 
![Screen Shot 2024-01-03 at 2 49 37 PM](https://github.com/wileyandco/thehumanarray/assets/146997680/ec0710a0-2771-42e1-a1e6-cc1909b7a778)

This one is similar to what you created, but with the slimmer moon shape for the buckets.
![Screen Shot 2024-01-03 at 2 51 58 PM](https://github.com/wileyandco/thehumanarray/assets/146997680/c4a8eb65-8e70-4ae3-98f7-60532da26790)

**Comment by wileyandco** [comment]
@CarrieTHA Thanks! I made some updates with that all in mind on https://www.thehumanarray.com/home-new

I do want to make sure it doesn't end up looking like a knock-off of the logo if you know what I mean. But the circle part does help to make it look like a water wheel as opposed to an abstract symbol. I'm free at 10 tomorrow to chat :)

**Comment by wileyandco** [comment]
@CarrieTHA set as homepage screenshot from our convo is here:



![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/7c93a5c9-05a4-414b-b4a8-228ed1f06cc9)

**Comment by wileyandco** [comment]
Putting this join link here for when we need to add back in subscriptions https://community.thehumanarray.com/sign_up
