### ISSUE TITLE
Add Amanda to About Us Page

### ISSUE THREAD

**Issue by CarrieTHA** [wileyandco/thehumanarray#30]
Amanda has written her bio and we'd like to get her up on the About Us page. Can you help me with that? 

Bio: 
Greetings, I'm Amanda Watson Johnson—a lifelong seeker of wisdom, perpetual student, flower
alchemist, human connector, and entrepreneur. With over two decades of experience in
customer service and sales, I've cultivated a diverse background that includes a flower essence
botanical line, alignment coaching, and podcast. As the host of the podcast "Chime in with
Amanda Watson Johnson", I passionately explore the dimensions of mind, body, and soul
wellness. Within this podcast, I navigate the intricacies of holistic well-being, weaving together
insights from both my personal journey and conversations with visionaries. My commitment
goes beyond my sales career, coaching, podcasting and flower alchemy; I am on a mission with
The Human Array to connect people with a network of coaches, healers, and thought leaders
who have played pivotal roles in my wellness journey and within the holistic health field.
Through The Human Array, I strive to empower others by facilitating transformative connections
and providing access to the invaluable support that has shaped my own path to well-being.

![AWJ_ChelseaLanePhotography-7](https://github.com/wileyandco/thehumanarray/assets/146997680/6b111cdf-4ca2-4710-aad7-34825c48095b)

I don't have her "fun" stuff yet, but will add as soon as I do!

**Comment by wileyandco** [comment]
Hey @CarrieTHA - this is updated on about us. I used a leaf for her icon to tie into her business' logo. Also, pretty sure the quotations go after the comma so changed this [ "Chime in with
Amanda Watson Johnson", I passionately ] to this [ "Chime in with
Amanda Watson Johnson," I passionately ]

Let me know if all set.

**Comment by CarrieTHA** [comment]
Fantastic! And yes, probably. It did that weird &-quote thing when I
pasted, so I was being hasty. Thanks for adjusting. I'll take a look and
let you know if there's any changes!

**Comment by CarrieTHA** [comment]
This looks great! I also gathered her fun stuff. 

Favorite snack: Freshly cut pineapple 
Favorite quote: "If you want to find the secrets of the universe, think in terms of frequency, energy and vibration." Nikola Tesla 
Favorite place to travel: Anywhere on the coast of France 
Astrology (sun, moon, rising): Sun: Scorpio, Moon: Gemini, Rising: Cancer 
Word that describes me: Inquisitive 
Guilty pleasure: Lavender Latte with whole milk or chocolate chip cookies

**Comment by wileyandco** [comment]
Hey @CarrieTHA Just went to updated this and saw you got in there. Just changed the quotation marks to the right ones and added the em dash. Digging back in over here. Let me know if you need anything else for Amanda besides the cards. Eventually I'd like this section to be a carousel, which will be easier in Wix Studio. I just checked and they are still tbd on when Editor X sites will be "two clicks to port over," but should be soon. 
<img width="875" alt="Screen Shot 2024-02-19 at 4 21 20 PM" src="https://github.com/wileyandco/thehumanarray/assets/78058722/169ba51b-cf19-4511-a7d3-261d1903e08b">

**Comment by CarrieTHA** [comment]
Awesome, thank you! I jumped in because Amanda wanted to feel official if
she was doing outreach. 😁 thank you for checking it and adjusting!!
