### ISSUE TITLE
Energetic Exchange Icon

### ISSUE THREAD

**Issue by CarrieTHA** [wileyandco/thehumanarray#40]
Hi! We want to create a space (maybe multiple in the future?) where Catalysts can swap services. i.e. I am Astrologist looking for a some Nutrition Guidance, would anyone be up for swapping / exchanging services? Like a reading for a session?

I wanted to differentiate this space from the other Catalyst conversation spaces. Thoughts on a different icon?

**Comment by wileyandco** [comment]
@CarrieTHA Ooh yes. How about one of these? The last one could have circular points on it. THA seems more like a fluid system than a this for that, but the simple arrows one would look great small and we could save and use something like the nebula when talking about the subscription model and contributions.

<img width="315" alt="Screen Shot 2024-04-03 at 10 04 29 AM" src="https://github.com/wileyandco/thehumanarray/assets/78058722/c5ef8880-7c2e-4acb-8f62-5300adfa52fe">
<img width="127" alt="Screen Shot 2024-04-03 at 10 04 36 AM" src="https://github.com/wileyandco/thehumanarray/assets/78058722/8d0909c9-fc48-45cf-ac7b-ae1a8e323f01">
<img width="323" alt="Screen Shot 2024-04-03 at 10 04 42 AM" src="https://github.com/wileyandco/thehumanarray/assets/78058722/3aabb4e6-0256-430b-8d23-db721b17bc9a">
<img width="303" alt="Screen Shot 2024-04-03 at 10 09 09 AM" src="https://github.com/wileyandco/thehumanarray/assets/78058722/d809f56f-b28b-4c0d-97ea-f1ed70afa3d3">

**Comment by CarrieTHA** [comment]
Yes! I like all of these, but the simple arrow circle one feels right for a
small icon for right now. I like the nebula for the subscription model too.
There is something I like about the last one also and I feel like the
points could be diamonds, aka arrows going both ways to show that things
are moving in all directions.


*Carrie Allen*
Founder
thehumanarray.com
IG: @thehumanarray

**Comment by wileyandco** [comment]
@CarrieTHA https://community.thehumanarray.com/spaces/13920955/feed and canva are updated with these 
![icon_catalystswap](https://github.com/wileyandco/thehumanarray/assets/78058722/cdaa9ff8-8e11-4111-8b84-b11e7722d514)
![icon_catalystswap@8x](https://github.com/wileyandco/thehumanarray/assets/78058722/2ef5a5db-1312-4cfe-a1fd-0f87e8d88474)
