### ISSUE TITLE
Catalyst Form Autoresponse Emails

### ISSUE THREAD

**Issue by CarrieTHA** [wileyandco/thehumanarray#41]
For both of the Jotforms, application and intake, Jotform sends an automated email to the Catalyst to let them know their form has been received. Can we brand / customize these emails to be ours instead of Jotforms? 

Settings > Emails > Autoresponder 1

**Comment by wileyandco** [comment]
Yes we can. And the intake email autorespond can also be the thank you for
completing, hey go pay if you haven't already, talk to you soon one.

**Comment by CarrieTHA** [comment]
LOL yup! With a link back to the payment page. Great call!

Here's the text for the application that Meg wrote with a tiny tweak, just so that it is in Github as well.

Thank you for your application. 
Now, we want to meet you!

Your next step is to schedule a 10-15 minute chat with one of our leadership team members.

You’ll receive an email from our team within 24 hours, with available time slots for the interview. 

We are looking so forward to connecting with you!
The Human Array Team

**Comment by wileyandco** [comment]
Got it!




*Jeannette Wiley Detwiler*
Owner & Designer

wileyand.co
***@***.***
linkedin.com/in/jeannettewiley
cell: 315-283-0648 <315-283-0648>

**Comment by wileyandco** [comment]
@CarrieTHA The approval flow in jotform for the catalyst intake form is broken. Are you in there or have things moving for meg and Sarah or can I remake it?


![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/dd4459f1-e785-4928-b532-1d7a34504bff)

**Comment by CarrieTHA** [comment]
Well shoot! No I am not in there, but I did sign in to see if I could find
a form someone thought they submitted but can't find. Go for it! I will
stay out :D


*Carrie Allen*
Founder
thehumanarray.com
IG: @thehumanarray
